import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full h-screen max-h-screen overflow-hidden flex-center relative">
        <div className="-translate-y-4">{children}</div>
      </body>
    </html>
  );
}
